active_border_color {{active_border_color}}
active_tab_background {{active_tab_background}}
active_tab_foreground {{active_tab_foreground}}
background {{background}}
bell_border_color {{bell_border_color}}
color0 {{color0}}
color1 {{color1}}
color10 {{color10}}
color11 {{color11}}
color12 {{color12}}
color13 {{color13}}
color14 {{color14}}
color15 {{color15}}
color2 {{color2}}
color3 {{color3}}
color4 {{color4}}
color5 {{color5}}
color6 {{color6}}
color7 {{color7}}
color8 {{color8}}
color9 {{color9}}
cursor {{cursor}}
cursor_text_color {{cursor_text_color}}
foreground {{foreground}}
inactive_border_color {{inactive_border_color}}
inactive_tab_background {{inactive_tab_background}}
inactive_tab_foreground {{inactive_tab_foreground}}
macos_titlebar_color {{macos_titlebar_color}}
mark1_background {{mark1_background}}
mark1_foreground {{mark1_foreground}}
mark2_background {{mark2_background}}
mark2_foreground {{mark2_foreground}}
mark3_background {{mark3_background}}
mark3_foreground {{mark3_foreground}}
scrollbar_handle_color {{scrollbar_handle_color}}
scrollbar_track_color {{scrollbar_track_color}}
selection_background {{selection_background}}
selection_foreground {{selection_foreground}}
tab_bar_background {{tab_bar_background}}
url_color {{url_color}}
wayland_titlebar_color {{wayland_titlebar_color}}
