
[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "BlexMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "BlexMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
# Share buffer with primary clipboard
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_title = true
# If set to "Both" it does not work
option_as_alt = "OnlyLeft"
#startup_mode = "Maximized"

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4

[general]
live_config_reload = true
import = ["~/.dotfiles/.config/alacritty/themes/themes/kanagawa_dragon.toml"]

[terminal]
