# Gaps
# Inner gaps between windows, outer gaps from monitor edges

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.bottom = 10
outer.top = [{ monitor.main = 10 }, 10]
outer.right = 10
outer.left = 10
