gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#79C0FF"
      - "bold"
    inactiveBorderColor:
      - "#8A92B2"
    searchingActiveBorderColor:
      - "#78DCE8"
      - "bold"
    optionsTextColor:
      - "#79C0FF"
    selectedLineBgColor:
      - "#3E526F"
    inactiveViewSelectedLineBgColor:
      - "#3E526F"
    cherryPickedCommitFgColor:
      - "#C8D3F5"
    cherryPickedCommitBgColor:
      - "#B691FA"
    markedBaseCommitFgColor:
      - "#C8D3F5"
    markedBaseCommitBgColor:
      - "#F5B600"
    unstagedChangesColor:
      - "#FF7B72"
    defaultFgColor:
      - "#C8D3F5"
