set -g @minimal_theme_bg_color "#0D1117"
set -g @minimal_theme_active_color "#79C0FF"
set -g @minimal_theme_inactive_color "#8A92B2"
set -g @minimal_theme_text_color "#C8D3F5"
set -g @minimal_theme_accent_color "#B691FA"
set -g @minimal_theme_border_color "#3E526F"
