# First, preload the image (this stays a flat line)
preload = /home/mattis/Pictures/wallpapers/unix.jpg

wallpaper {
    monitor = eDP-1
    path = /home/mattis/Pictures/wallpapers/unix.jpg
    fit_mode = cover
    # fit_mode = contain
}

wallpaper {
    monitor = DP-2
    path = /home/mattis/Pictures/wallpapers/unix.jpg
    fit_mode = cover
}
