set -g @minimal_theme_bg_color "#002B36"
set -g @minimal_theme_active_color "#268BD2"
set -g @minimal_theme_inactive_color "#657B83"
set -g @minimal_theme_text_color "#839496"
set -g @minimal_theme_accent_color "#D33682"
set -g @minimal_theme_border_color "#073642"
