set -g @minimal_theme_bg_color "#1A1B26"
set -g @minimal_theme_active_color "#7AA2F7"
set -g @minimal_theme_inactive_color "#8A92B2"
set -g @minimal_theme_text_color "#C8D3F5"
set -g @minimal_theme_accent_color "#BB9AF7"
set -g @minimal_theme_border_color "#414868"
