[general]
import = [
    "./themes/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true


[font]
size = 14

[font.normal]
# family = "Monaspace Neon NF"
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
# family = "Monaspace Neon NF"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
# family = "Monaspace Neon NF"
family = "JetBrainsMono Nerd Font"


[font.offset]
x = 0
y = 0


[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" },
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }]

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_title = true
option_as_alt = "Both"
#startup_mode = "Maximized"

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4
