set -g @minimal_theme_bg_color "{{bg}}"
set -g @minimal_theme_active_color "{{active}}"
set -g @minimal_theme_inactive_color "{{inactive}}"
set -g @minimal_theme_text_color "{{text}}"
set -g @minimal_theme_accent_color "{{accent}}"
set -g @minimal_theme_border_color "{{border}}"
