github.com:
    git_protocol: https
    users:
        brandsoy:
            oauth_token: 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
    user: brandsoy
    oauth_token: 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
