github.com:
    git_protocol: ssh
    users:
        brandsoy:
            oauth_token: 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
    user: brandsoy
    oauth_token: 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
