#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

# Settings
cache = false

[[session]]
name = "Nvim Config"
path = "~/.config/nvim"
startup_command = "la"

[[session]]
name = "Dotfiles"
path = "~/dotfiles"
startup_command = "la"

#Work  Projects
[[session]]
name = "Saga Connect"
path = "/Users/mattis/Developer/git/work/SagaConnect/saga-connect"
startup_command = "la"

[[session]]
name = "Insight"
path = "/Users/mattis/Developer/git/work/FBH-Insigth/FBH-Insight"
startup_command = "la"

[[session]]
name = "Sharepoint Contract Management"
path = "/Users/mattis/Developer/git/work/sharepoint-contract-management"
startup_command = "la"

[[session]]
name = "Sharepoint Project Management"
path = "/Users/mattis/Developer/git/work/sharepoint-project-management"
startup_command = "la"

# Home Projects
[[session]]
name = "Homelab"
path = "/Users/mattis/Developer/git/personal/homelab"
startup_command = "la"
