#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

# Settings
cache = false

# Configs
[[session]]
name = "Tmux Config"
path = "~"
startup_command = "nvim .tmux.conf"
preview_command = "bat --color=always ~/.tmux.conf"

[[session]]
name = "Nvim Config"
path = "~/.config/nvim"
startup_command = "la"

[[session]]
name = "Aerospace Config"
path = "~/.config/aerospace"
startup_command = "nvim aerospace.toml"
preview_command = "bat --color=always ~/.config/aerospace/aerospace.toml"

[[session]]
name = "Sesh Config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "Dotfiles"
path = "~/dotfiles"
startup_command = "la"

#Work  Projects
[[session]]
name = "Saga Connect"
path = "/Users/mattis/Developer/git/work/SagaConnect/saga-connect"
startup_command = "la"

[[session]]
name = "Insight"
path = "/Users/mattis/Developer/git/work/FBH-Insigth/FBH-Insight"
startup_command = "la"

[[session]]
name = "Dev Work"
path = "/Users/mattis/Developer/git/work"
startup_command = "la"

[[session]]
name = "Dev Personal"
path = "/Users/mattis/Developer/git/personal"
startup_command = "la"

[[session]]
name = "Sharepoint Contract Manager"
path = "/Users/mattis/Developer/git/work/sharepoint-contract-manager"
startup_command = "la"

[[session]]
name = "Sharepoint Project Manager"
path = "/Users/mattis/Developer/git/work/sharepoint-project-manager"
startup_command = "la"

# Home Projects
[[session]]
name = "Homelab"
path = "/Users/mattis/Developer/git/personal/homelab"
startup_command = "la"

