[settings]
idiomatic_version_file_enable_tools = ["ruby"]
experimental = true

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true

[settings.ruby]

[tools]
ansible = "latest"
bun = "latest"
dotnet = "latest"
go = "latest"
gum = "latest"
node = "lts"
npm = "latest"
pnpm = "latest"
python = "latest"
uv = "latest"
terraform = "latest"
"npm:@typescript/native-preview" = "beta"
"npm:@typespec/compiler" = "latest"
"dotnet:dotnet-ef" = "latest"
