palette = "SupaTheme"

[palettes.SupaTheme]
black = "{{black}}"
red = "{{red}}"
green = "{{green}}"
yellow = "{{yellow}}"
blue = "{{blue}}"
purple = "{{purple}}"
cyan = "{{cyan}}"
white = "{{white}}"
bright-black = "{{bright_black}}"
bright-red = "{{bright_red}}"
bright-green = "{{bright_green}}"
bright-yellow = "{{bright_yellow}}"
bright-blue = "{{bright_blue}}"
bright-purple = "{{bright_purple}}"
bright-cyan = "{{bright_cyan}}"
bright-white = "{{bright_white}}"
