#################
### AUTOSTART ###
#################

# Set GTK theme and preferences early
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Tokyo-Night' # Or your exact theme name
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
# exec-once = gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
exec-once = gsettings set org.gnome.desktop.interface cursor-theme "default"
exec-once = gsettings set org.gnome.desktop.interface font-name "Adwaita Sans 11"

exec-once = uwsm app -- swaync
exec-once = uwsm app -- hyprpaper
exec-once = sleep 1 && uwsm app -- waybar
exec-once = systemctl --user start hyprpolkitagent
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- vicinae server
exec-once = sleep 3 && uwsm app -- nm-applet --indicator
exec-once = sleep 3 && uwsm app -- blueman-applet


# Run workspace setup script at startup
exec-once = ~/.config/hypr/scripts/monitor_workspace_setup.sh

