[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true

[settings.ruby]

[tools]
bun = "latest"
dotnet = "latest"
go = "latest"
gum = "latest"
node = "latest"
npm = "latest"
python = "latest"
uv = "latest"
ruff = "latest"
terraform = "latest"
lua-language-server = "latest"
stylua = "latest"
terraform-ls = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/segmentio/golines" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"npm:@typescript/native-preview" = "latest"
"npm:@typespec/compiler" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:tailwindcss-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:svelte-language-server" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:prettier" = "latest"
