# Performance
macos_option_as_alt no
repaint_delay    8
input_delay      1
sync_to_monitor  no

# Font
# BEGIN_KITTY_FONTS
font_family      family="GeistMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
adjust_line_height 125%

# Window
window_margin_width 5
hide_window_decorations yes
macos_show_window_title_in: none
scrollback_lines 2000
disable_ligatures always

# Theme
# BEGIN_KITTY_THEME
# Tokyo Night
include tokyonight_night.conf
# END_KITTY_THEME
