set -g @minimal_theme_bg_color "#eff1f5"
set -g @minimal_theme_active_color "#1e66f5"
set -g @minimal_theme_inactive_color "#8c8fa1"
set -g @minimal_theme_text_color "#4c4f69"
set -g @minimal_theme_accent_color "#1e66f5"
set -g @minimal_theme_border_color "#bcc0cc"
