return {
	settings = {
		yaml = {
			schemas = {
				["https://json.schemastore.org/github-workflow.json"] = ".github/workflows/*.{yml,yaml}",
				["https://json.schemastore.org/github-action.json"] = ".github/action.{yml,yaml}",
				["https://json.schemastore.org/composer.json"] = "composer.json",
				["https://json.schemastore.org/docker-compose.json"] = "docker-compose*.{yml,yaml}",
				["https://json.schemastore.org/kubernetes.json"] = "/*.{yml,yaml}",
				["https://json.schemastore.org/helmfile.json"] = "helmfile.{yml,yaml}",
				["https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.24.3-standalone-strict/all.json"] = "/*.{yml,yaml}",
			},
			validate = true,
			format = {
				enable = true,
				singleQuote = false,
				bracketSpacing = true,
				proseWrap = "preserve",
				printWidth = 100,
			},
			hover = true,
			completion = true,
			customTags = {
				"!Base64 scalar",
				"!Cidr scalar",
				"!FindInMap sequence",
				"!GetAtt scalar",
				"!GetAZs mapping",
				"!ImportValue scalar",
				"!Join sequence",
				"!Ref scalar",
				"!Select sequence",
				"!Split sequence",
				"!Sub scalar",
				"!Transform mapping",
				"!And sequence",
				"!Equals sequence",
				"!If sequence",
				"!Not sequence",
				"!Or sequence",
			},
		},
	},
	filetypes = { "yaml", "yml" },
}
