wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/arch-dual.png
    fit_mode = contain
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/arch-dual.png
    fit_mode = contain
}
