# First, preload the image (this stays a flat line)
preload = /home/mattis/Pictures/wallpapers/fedora.png

wallpaper {
    monitor = eDP-1
    path = /home/mattis/Pictures/wallpapers/fedora.png
    fit_mode = cover
    # fit_mode = contain
}

# wallpaper {
#     monitor = DP-2
#     path = ~/Pictures/wallpapers/fedora.png
#     fit_mode = contain
# }
