#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us,no
    kb_options = grp:ctrl_space_toggle

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

input {
    repeat_rate = 50   # Repeat rate in repeats per second (default: 25)
    repeat_delay = 200 # Delay before repeating starts in milliseconds (default: 600)
}   

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
