# Gaps
# Inner gaps between windows, outer gaps from monitor edges

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.bottom = 5
outer.top = [{ monitor.main = 5 }, 5]
outer.right = 5
outer.left = 5
