#!/usr/bin/env bash
set -euo pipefail

# Generate SupaTheme's non-Neovim theme files from the Neovim palette.
# Edit the palette here, then run this script:
#   ./scripts/generate-supatheme.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THEME_DIR="${SCRIPT_DIR}/../roles/config/.config/theme-sync/themes/SupaTheme"
PALETTE="${THEME_DIR}/lua/SupaTheme/palette.lua"

python3 - "$THEME_DIR" "$PALETTE" <<'PY'
from pathlib import Path
import re
import sys

root = Path(sys.argv[1]).resolve()
palette_file = Path(sys.argv[2]).resolve()
text = palette_file.read_text()

# Parse literal colour entries from palette.lua. Aliases and derived colours
# are intentionally resolved below (for example, number = keyword).
colors = dict(re.findall(r'^\s*([a-z_]+)\s*=\s*"(#[0-9a-fA-F]{6})"', text, re.M))
colors["number"] = colors["keyword"]

required = {
    "bg", "fg", "fg_bright", "border", "surface", "bg_alt", "grey",
    "grey_warm", "grey_light", "silver", "white", "black", "keyword",
    "func", "type", "string", "signal", "error", "warning", "info",
    "hint", "ok",
}
missing = sorted(required - colors.keys())
if missing:
    raise SystemExit(f"Missing palette entries: {', '.join(missing)}")

c = colors

def write(path: str, content: str) -> None:
    destination = root / path
    destination.write_text(content.rstrip() + "\n")
    print(destination)

# ANSI mapping used by the terminal themes.
ansi = {
    0: c["black"], 1: c["error"], 2: c["ok"], 3: c["signal"],
    4: c["func"], 5: c["type"], 6: c["func"], 7: c["silver"],
    8: c["grey"], 9: c["error"], 10: c["ok"], 11: c["warning"],
    12: c["info"], 13: c["type"], 14: c["func"], 15: c["white"],
}

write("extras/alacritty/SupaTheme.toml", f'''# Generated by scripts/generate-supatheme.sh
[colors.primary]
background = "{c['bg']}"
foreground = "{c['fg']}"

[colors.cursor]
cursor = "{c['fg']}"
text = "{c['bg']}"

[colors.selection]
background = "{c['border']}"
text = "{c['fg']}"

[colors.normal]
black = "{ansi[0]}"
red = "{ansi[1]}"
green = "{ansi[2]}"
yellow = "{ansi[3]}"
blue = "{ansi[4]}"
magenta = "{ansi[5]}"
cyan = "{ansi[6]}"
white = "{ansi[7]}"

[colors.bright]
black = "{ansi[8]}"
red = "{ansi[9]}"
green = "{ansi[10]}"
yellow = "{ansi[11]}"
blue = "{ansi[12]}"
magenta = "{ansi[13]}"
cyan = "{ansi[14]}"
white = "{ansi[15]}"
''')

indexed = '\n'.join(f'[[colors.indexed_colors]]\nindex = {i}\ncolor = "{value}"\n' for i, value in {
    16: c['grey_light'], 17: c['signal'], 18: c['bg_alt'], 19: c['border'],
    20: c['grey'], 21: c['silver'],
}.items())
path = root / "extras/alacritty/SupaTheme.toml"
path.write_text(path.read_text().rstrip() + "\n\n" + indexed.rstrip() + "\n")

write("extras/ghostty/SupaTheme", f'''# Generated by scripts/generate-supatheme.sh
# name = "SupaTheme"

{chr(10).join(f"palette = {i}={ansi[i]}" for i in range(16))}
palette = 16={c['grey_light']}
palette = 17={c['signal']}
palette = 18={c['bg_alt']}
palette = 19={c['border']}
palette = 20={c['grey']}
palette = 21={c['silver']}

background = {c['bg']}
foreground = {c['fg']}
cursor-color = {c['fg']}
selection-background = {c['border']}
selection-foreground = {c['fg']}
''')

write("extras/kitty/SupaTheme.conf", f'''# Generated by scripts/generate-supatheme.sh
foreground            {c['fg']}
background            {c['bg']}
cursor                {c['fg']}
cursor_text_color     {c['bg']}
selection_foreground  {c['fg']}
selection_background  {c['border']}
tab_bar_background    {c['bg']}
active_tab_foreground {c['fg']}
active_tab_background {c['bg_alt']}
inactive_tab_foreground {c['grey']}
inactive_tab_background {c['bg']}
bell_border_color     {c['error']}

{chr(10).join(f"color{i}  {ansi[i]}" for i in range(16))}
''')

write("extras/fzf/SupaTheme.sh", f'''# Generated by scripts/generate-supatheme.sh
export FZF_DEFAULT_OPTS=" \\
--color=bg+:{c['bg_alt']},bg:{c['bg']},spinner:{c['grey_light']},hl:{c['signal']} \\
--color=fg:{c['fg']},header:{c['signal']},info:{c['info']},pointer:{c['grey_light']} \\
--color=marker:{c['hint']},fg+:{c['silver']},prompt:{c['func']},hl+:{c['signal']} \\
--color=border:{c['bg']} \\
--multi"
''')

write("tmux.theme.conf", f'''# Generated by scripts/generate-supatheme.sh
# SupaTheme integration for the minimal tmux status bar.
set -g @minimal_theme_bg_color "{c['bg']}"
set -g @minimal_theme_active_color "{c['func']}"
set -g @minimal_theme_inactive_color "{c['grey']}"
set -g @minimal_theme_text_color "{c['fg']}"
set -g @minimal_theme_accent_color "{c['type']}"
set -g @minimal_theme_border_color "{c['border']}"
''')

# theme-sync uses this value when applying the tmux theme.
env = root / "theme.env"
env_text = env.read_text()
env_text = re.sub(r'^TMUX_BACKGROUND=.*$', f'TMUX_BACKGROUND="{c["bg"]}"', env_text, flags=re.M)
env.write_text(env_text)
print(env)
PY

echo "SupaTheme generated from: $PALETTE"
echo "Apply it with: ./scripts/theme-sync.sh apply"
