set -g @minimal_theme_bg_color "#FAF4ED"
set -g @minimal_theme_active_color "#0350AE"
set -g @minimal_theme_inactive_color "#908CAA"
set -g @minimal_theme_text_color "#575279"
set -g @minimal_theme_accent_color "#907AA9"
set -g @minimal_theme_border_color "#55667B"
