set -g @minimal_theme_bg_color "#FFFFFF"
set -g @minimal_theme_active_color "#0350AE"
set -g @minimal_theme_inactive_color "#70818F"
set -g @minimal_theme_text_color "#2B343F"
set -g @minimal_theme_accent_color "#A268F6"
set -g @minimal_theme_border_color "#55667B"
