return function()
  require("which-key").setup()
  local wk = require("which-key")
  wk.add({
    { "<leader>s", group = "Symbols" },
    { "<leader>l", group = "LSP" },
    { "<leader>lt", desc = "TypeSpec: Show Emitter Output" },
    { "<leader>lT", desc = "TypeSpec: Compile (emit)" },
    { "<leader>lq", desc = "Diagnostics to Location List" },
    { "<leader>g", group = "Go" },
    { "<leader>d", group = "Debug" },
    { "<leader>gb", desc = "Go: Build" },
    { "<leader>gr", desc = "Go: Run" },
    { "<leader>gt", desc = "Go: Test All" },
    { "<leader>gT", desc = "Go: Test File" },
    { "<leader>gn", desc = "Go: Test Nearest" },
    { "<leader>gi", desc = "Go: Organize Imports" },
    { "<leader>gf", desc = "Go: Format (imports)" },
    { "<leader>ga", desc = "Go: Add json tags" },
    { "<leader>gA", desc = "Go: Remove json tags" },
    { "<leader>gc", desc = "Go: Generate comment" },
    { "<leader>gs", desc = "Go: Fill struct" },
    { "<leader>gS", desc = "Go: Add if err" },
    { "<leader>go", desc = "Go: Toggle test/source" },
    { "<F5>", desc = "DAP: Continue" },
    { "<F9>", desc = "DAP: Toggle Breakpoint" },
    { "<F10>", desc = "DAP: Step Over" },
    { "<F11>", desc = "DAP: Step Into" },
    { "<F12>", desc = "DAP: Step Out" },
    { "<leader>db", desc = "DAP: Toggle Breakpoint" },
    { "<leader>dc", desc = "DAP: Continue" },
    { "<leader>do", desc = "DAP: Step Over" },
    { "<leader>di", desc = "DAP: Step Into" },
    { "<leader>dO", desc = "DAP: Step Out" },
    { "<leader>dr", desc = "DAP: Toggle REPL" },
    { "<leader>du", desc = "DAP: Toggle UI" },
    { "<leader>dt", desc = "DAP: Debug Go Test" },
    { "<leader>dT", desc = "DAP: Debug Last Go Test" },
  })
end
