set -g @minimal_theme_bg_color "#1B1917"
set -g @minimal_theme_active_color "#6099C0"
set -g @minimal_theme_inactive_color "#867A74"
set -g @minimal_theme_text_color "#B4BDC3"
set -g @minimal_theme_accent_color "#B278A7"
set -g @minimal_theme_border_color "#403833"
