set -g @minimal_theme_bg_color "#282c34"
set -g @minimal_theme_active_color "#61afef"
set -g @minimal_theme_inactive_color "#7f848e"
set -g @minimal_theme_text_color "#abb2bf"
set -g @minimal_theme_accent_color "#c678dd"
set -g @minimal_theme_border_color "#3a404b"
