#################
### AUTOSTART ###
#################

# Autostart necessary: processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = elephant
exec-once = swaync
exec-once = hyprpaper
exec-once = sleep 1 && waybar
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = walker --gapplication-service

# Run workspace setup script at startup
exec-once = /home/mattis/dotfiles/home/config/.config/hypr/scripts/monitor_workspace_setup.sh 
