#################
### AUTOSTART ###
#################

exec-once = swaync
exec-once = hyprpaper
exec-once = sleep 1 && waybar
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = vicinae server

# Run workspace setup script at startup
exec-once = ~/.config/hypr/scripts/monitor_workspace_setup.sh 

# Ensure the D-Bus session knows about your Wayland environment
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Start the GNOME Keyring daemon (if you chose gnome-keyring)
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets

