wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/wallhaven-yx9log.jpg
    fit_mode = contain
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/wallhaven-gpljoq.png
    fit_mode = contain
}
