################
### MONITORS ###
################
# "hyprland/window": {
#     "separate-outputs": true
# },
# See https://wiki.hypr.land/Configuring/Monitors/
# External monitor
# monitor = DP-2, 2560x1440@75, -2560x0, 1
monitor = DP-2, 5120x1440@75, 0x0, 1
monitor = DP-3, 2560x1440@75, -2560x0, 1
# # Internal monitor
# # monitor = eDP-1,1920x1200@60,1840x1440,1
# bindl = ,switch:on[lid], exec, hyprctl keyword monitor "eDP-1,disable"
# bindl = ,switch:off[lid], exec, hyprctl keyword monitor "eDP-1,1920x1200@60,1840x1440,1"
# # Fallback for any unspecified monitors
# monitor=,preferred,auto,1

# Internal monitor configuration
monitor = eDP-1, 1920x1200@60, 1840x1440, 1

# Trigger when the lid is CLOSED (Switch is ON)
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"

# Trigger when the lid is OPENED (Switch is OFF)
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, 1920x1200@60, 1840x1440, 1"

# Fallback for any unspecified monitors
monitor = , preferred, auto, 1
