################
### MONITORS ###
################
# "hyprland/window": {
#     "separate-outputs": true
# },
# See https://wiki.hypr.land/Configuring/Monitors/
# External monitor
monitor = DP-2, 2560x1440@75, -2560x0, 1
monitor = DP-3, 2560x1440@75, -2560x0, 1
# Internal monitor
monitor = eDP-1,1920x1200@60,0x0,1

# Fallback for any unspecified monitors
monitor=,preferred,auto,1
